# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1c3c9c8d7c36716c265091ba81939417fdf3e62b971774e8b43e8e9136bd6f99f4384ffd9d85dc0cdbb6f0a31abf297dd6123b02d9e27b1d2f01ea8321e06e0

test:
  secret_key_base: 406e4d13cd308bcebaf527b96f2376111ca1236d96a74d6ac43231f15fc8d5e41eab02da5f64f09a5e241305393fecc53fb761037b4345fcaf9bf8507fea6a63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
